// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClntOwbcDx7BOIK5ORK2AdZz6oRY5VE3Q',
    appId: '1:156957460922:web:e1b08f529a12a37db4f583',
    messagingSenderId: '156957460922',
    projectId: 'sani-hub',
    authDomain: 'sani-hub.firebaseapp.com',
    storageBucket: 'sani-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkHmj7JTvB4ROxJZdl5pRacTcfVMPff_Q',
    appId: '1:156957460922:android:a5cd5576e867ffe6b4f583',
    messagingSenderId: '156957460922',
    projectId: 'sani-hub',
    storageBucket: 'sani-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6MAhU5uMWKxNfWfBjrPUhfn84XFTBdY',
    appId: '1:156957460922:ios:22dd4e310985fb3cb4f583',
    messagingSenderId: '156957460922',
    projectId: 'sani-hub',
    storageBucket: 'sani-hub.firebasestorage.app',
    iosClientId: '156957460922-75gsd7cm2mtedh1lq3shr7enu9mq3g7v.apps.googleusercontent.com',
    iosBundleId: 'com.sani.med.sanihub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClntOwbcDx7BOIK5ORK2AdZz6oRY5VE3Q',
    appId: '1:156957460922:web:f68c12d7edefa659b4f583',
    messagingSenderId: '156957460922',
    projectId: 'sani-hub',
    authDomain: 'sani-hub.firebaseapp.com',
    storageBucket: 'sani-hub.firebasestorage.app',
  );
}
